<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>Tumblr OAuth Example</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<link rel="stylesheet" href="style.css">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
	<script type="text/javascript">
	function myFunction() {
    var x = document.getElementById('shower');
    if (x.style.display === 'block') {
        x.style.display = 'none';
    } else {
        x.style.display = 'block';
    }
}	
	</script>
  </head>
  <body>
    <div class="index">
      <h2>Welcome to a Tumblr OAuth PHP example.</h2>

      <p>This site is a basic showcase of Tumblrs OAuth authentication method. <br/>If you are having issues try <a href='./logout.php'>clearing your session</a>.</p>

      <p>
        links:
        <a href='https://github.com/alperensert/tumblr-oauth'>Source Code</a> |
        <a href='https://github.com/nquinlan/tumblr-oauth/blob/master/DOCUMENTATION'>Documentation</a> |
        Contact with Twitter <a href='https://twitter.com/alperensert99'>@alperensert99</a>
      </p>
	 </div>
	<div id="wrap">
